<?php
$title = 'Connexion';
$this->headTitle($title);
?>
<center><h1><?php echo $this->escapeHtml($title); ?></h1></center>
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
                    'login/process', array(
                'action' => 'authenticate',
                    )
    ));
    $form->prepare();
?>
    
<div class="asideGestion">
     <?php
    echo '<br />';
    if ($this->messages) {
        foreach ($this->messages as $message) {
            echo $message . '<br />';
        }
        echo '<br />';
    }

    echo $this->form()->openTag($form);
//echo $this->formCollection($form);
    echo $this->formRow($form->get('username'));
    echo '<br />';
    echo $this->formRow($form->get('password'));
    echo '<br />';
    echo $this->formRow($form->get('rememberme'));
    echo '<br />';
    //echo $this->formRow($form->get('submit'));
    ?>
    <input class="btn btn-success" type="submit" name="submit" id="submitbutton" value="Se connecter" />
    <?php
    echo $this->form()->closeTag();
    ?>
    <br />
    <p>Pas encore membre ? <a href="<?php echo $this->url('utilisateur', array('action' => 'index')); ?>" class="btn btn-success">Inscription</a></p>
</div>

