<?php
$title = 'Ajouter une Douche';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('extra', array('action' => 'adddouche', 'idChambre' => $idChambre)));
$form->prepare();
?>

<div class="asideGestion">
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('idChambre'));
    echo '<br />';
    echo $this->formHidden($form->get('idDouche'));
    echo '<br />';
    echo $this->formRow($form->get('prixDouche'));
    echo '<br />';
 
    ?>
    <input class="btn btn-success" type="submit" name="submit" id="submitbutton" value="Ajouter" />
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
