<?php
$title = 'Modifier une television';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;

$form->setAttribute('action', $this->url('extra', array('action' => 'edittelevision', 'idHotel' => $idHotel, 'idChambre' => $this->idChambre, 'idDouche' => $this->idTelevision)));
$form->prepare();
?>

<div class="asideGestion">
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('idChambre'));
    echo '<br />';
    echo $this->formHidden($form->get('idTelevision'));
    echo '<br />';
    echo $this->formRow($form->get('prixTelevision'));
    echo '<br />';
    ?>
    <input class="btn btn-success" type="submit" name="submit" id="submitbutton" value="Modifier" />
    <a href="<?php echo $this->url('extra', array('idHotel' => $idHotel, 'idChambre' => $idChambre)); ?>" class="btn btn-success">Retour</a>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>