<?php
$title = "Gestion des extras de la chambre n°" . $this->escapeHtml($idChambre);
$adresse = "http://localhost/HotelierJson/public/extra//1/" . $this->escapeHtml($idHotel);
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?> <a href=<?php echo $adresse ?> class="btn btn-success">Normal</a></h1>
<center>
    <?php
    echo"--- Douche ---";
    echo $douche;

    echo"--- Television ---";
    echo $television;

    echo"--- Frigo ---";
    echo $frigo;

    echo"--- Baignoire---";
    echo $baignoire;
    ?>
</center>


