<?php

 $title = 'Mes Hôtels';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Ajouter un hôtel</a>
 </p>

 <table class="table">
 <tr>
     <th>Identifiant de l'adminsitrateur</th>
     <th>Identifiant de l'hôtel</th>
     <th>Nom de l'hôtel</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->idAdministrateur);?></td>
     <td><?php echo $this->escapeHtml($album->idHotel);?></td>
     <td><?php echo $this->escapeHtml($album->nomHotel);?></td>
     <td>
         <p>
             <a href="<?php echo $this->url('album', array('action'=>'edit', 'id' => $album->idHotel));?>">Modifier</a>
            |
            <a href="<?php echo $this->url('album', array('action'=>'delete', 'id' => $album->idHotel));?>">Supprimer</a>
         </p>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>