<?php
$title = "S'inscrire";
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('utilisateur', array('action' => 'add')));
$form->prepare();

if (isset($message)) {
    echo $message . '<br />';
    echo '<br />';
}

echo $this->form()->openTag($form);
echo $this->formRow($form->get('nom'));
echo '<br />';
echo $this->formRow($form->get('motDePasse'));
echo '<br />';
echo $this->formRow($form->get('mdp_check'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
