<?php
$title = 'Ajouter une chambre';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('chambre', array('action' => 'add', 'idHotel' => $idHotel)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idChambre'));
echo '<br />';
echo $this->formHidden($form->get('idHotel'));
echo '<br />';
echo $this->formRow($form->get('nomChambre'));
echo '<br />';
echo $this->formRow($form->get('type'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
