<?php

 $title = 'Modifier une chambre';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'chambre',
     array(
         'action' => 'edit',
         'idChambre' => $this->idChambre,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('idHotel'));
 echo '<br />';
 echo $this->formHidden($form->get('idChambre'));
 echo $this->formRow($form->get('nomChambre'));
 echo '<br />';
 echo $this->formRow($form->get('type'));
 echo '<br />';
 echo $this->formSubmit($form->get('submit'));
 //echo $this->formSubmit($form->get('cancel'));
 echo $this->form()->closeTag();
