<?php
$title = 'Modifier une chambre';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
                'chambre', array(
            'action' => 'edit',
            'idHotel' => $this->idHotel,
            'idChambre' => $this->idChambre,
                )
));
$form->prepare();
?>

<div class="asideGestion">
    <?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('idHotel'));
    echo '<br />';
    echo $this->formHidden($form->get('idChambre'));
    echo $this->formRow($form->get('nomChambre'));
    echo '<br />';
    echo $this->formRow($form->get('type'));
    echo '<br />';
    ?>
    <input class="btn btn-success" type="submit" name="submit" id="submitbutton" value="Modifier" />
    <a href="<?php echo $this->url('chambre', array('idHotel' => $idHotel)); ?>" class="btn btn-success">Retour</a>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>