<?php
$title = "Gestion des chambres de l'hôtel n°" . $this->escapeHtml($idHotel) . " - Json";
$this->headTitle($title);
$adresse = "http://localhost/HotelierJson/public/chambre//" . $this->escapeHtml($idHotel);
$affichage = "\"http://localhost/HotelierJson/public/chambre/listeChambreJson/" . $this->escapeHtml($idHotel) . "\"";
?>

<script>
    var app = angular.module('main', ['ngTable']).
            controller('DemoCtrl', function ($scope, ngTableParams, $http) {

                $http({method: 'GET', url: '/HotelierJson/public/chambre/listeChambreJson/<?php echo $this->escapeHtml($idHotel); ?>'}).
                        success(function (data) {
                            $scope.tableParams = new ngTableParams({
                                page: 1, // show first page
                                count: 5 // count per page
                            }, {
                                total: data.length, // length of data
                                getData: function ($defer, params) {
                                    $defer.resolve(data.slice((params.page() - 1) * params.count(), params.page() * params.count()));
                                }
                            });
                        }).
                        error(function (data) {
                        });
            });
</script>

<h1><?php echo $this->escapeHtml($title); ?> <a href=<?php echo $adresse ?> class="btn btn-success">Normal</a></h1>

<center>
    <!-- Arnaud Code Edit-->
    <body ng-app="main">
        <div ng-controller="DemoCtrl">
            <p><strong>Page n°</strong> {{tableParams.page()}} <strong></p>
            <p>Nombre de chambres par page :</strong> {{tableParams.count()}}</p>

            <table ng-table="tableParams" class="table ng-table-responsive table-condensed table-hover table-bordered table-striped">
                <tr ng-repeat="chambre in $data">
                    <td data-title="'Identifiant'">{{chambre.idChambre}}</td>
                    <td data-title="'Hotel'">{{chambre.idHotel}}</td>
                    <td data-title="'Nom'">{{chambre.nomChambre}}</td>
                    <td data-title="'Type'">{{chambre.type}}</td>
                    </td>
                </tr>
            </table>
        </div>
        <p>Par Corentin sur un code édité par Arnaud. On remercie Lucille pour son soutien !</p>
    </body>
</center>
