<?php
$title = "Gestion des chambres de l'hôtel n°" . $this->escapeHtml($idHotel);
$this->headTitle($title);
$tri = 0;
$adresse = "http://localhost/HotelierJson/public/chambre/indexjson/" . $this->escapeHtml($idHotel);
?>
<h1><?php echo $this->escapeHtml($title); ?> <a href=<?php echo $adresse ?> class="btn btn-success">Json</a></h1>
<p>
    <a href="<?php echo $this->url('chambre', array('action' => 'add', 'idHotel' => $idHotel)); ?>" class="btn btn-success">Ajouter une chambre</a>
    <a href="<?php echo $this->url('hotel'); ?>" class="btn btn-success">Retour</a>
</p>
<?php
switch ($tri) {
    case 0:
        break;
    case 1:
        break;
}
?>
<center>
    <?php foreach ($chambres as $chambre) : ?>
        <div class="asideChambre"><div class="prix">Prix : <?php echo $this->escapeHtml($chambre->type) * 58; ?> €</div>
            <table>
                <tr>
                    <td>
                        <a href="<?php echo $this->url('extra', array('action' => 'index', 'idHotel' => $chambre->idHotel, 'idChambre' => $chambre->idChambre)); ?>" class="btn btn-success boutonGauche bbb">Extras</a>
                        <a href="<?php echo $this->url('chambre', array('action' => 'edit', 'idHotel' => $chambre->idHotel, 'idChambre' => $chambre->idChambre)); ?>" class="btn btn-success boutonGauche bbb">Modifier</a>
                        <a href="<?php echo $this->url('chambre', array('action' => 'delete', 'idHotel' => $chambre->idHotel, 'idChambre' => $chambre->idChambre)); ?>" class="btn btn-success boutonGauche bbb">Supprimer</a>
                    </td>
                </tr>
                <tr>
                    <td rowspan="3">
                        <img src="<?php
                        $b = 1 + $this->escapeHtml($chambre->idChambre) % 30;
                        echo $this->basePath('img/Chambres/' . $b . '.jpg')
                        ?>" alt="Zend Framework 2" class="imgChambre"/>
                    </td>

                    <td class="Chambre" rowspan="3">
                        <h3><?php echo $this->escapeHtml($chambre->nomChambre); ?></h3>
                        <p>Chambre n°<?php echo $this->escapeHtml($chambre->idChambre); ?></p>
                        <p>Type <?php echo $this->escapeHtml($chambre->type); ?></p>
                    </td>
                </tr>
            </table>
        </div>
    <?php endforeach; ?>
</center>