<?php

use Application\Module;

echo $this->doctype();
?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Hôtelier')->setSeparator(' | ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/ng-table.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/angular.min.js')
                ->prependFile($this->basePath() . '/js/ng-table.min.js')
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/log2.png') ?>" alt="Hotelier" class="log"/>&nbsp;<?php echo $this->translate('Hôtelier') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php if (Module::$utilisateur) { ?><li><a href = "<?php echo $this->url('application') ?>"><?php echo $this->translate('Accueil') ?></a></li><?php } ?>
                        <?php if (Module::$utilisateur) { ?><li><a href="<?php echo $this->url('hotel') ?>"><?php echo $this->translate('Mes Hôtels') ?></a></li><?php } ?>
                    </ul>
                    <?php if (Module::$utilisateur) { ?><div class="infos">Connecté en tant que <strong><?php echo Module::$utilisateur->nom; ?></strong> - <a href="<?php echo $this->url('login/process', array('action' => 'logout')); ?>" class="deco">Déconnexion</a></div><?php } ?>
                </div>
            </div>

        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <center><p>&copy; <?php echo date('Y') ?> <b>Lucille Guillot</b>, <b>Corentin Marechal</b> et <b>Arnaud Favier</b>. Tout droits réservés.</p></center>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
