<?php

 $title = 'Ajouter un hôtel';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('hotel', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('idAdministrateur'));
 echo '<br />';
 echo $this->formHidden($form->get('idHotel'));
 echo '<br />';
 echo $this->formRow($form->get('nomHotel'));
 echo '<br />';
 echo $this->formSubmit($form->get('submit'));
 //echo $this->formSubmit($form->get('cancel'));
 echo $this->form()->closeTag();