<?php
$title = 'Ajouter un hôtel';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('hotel', array('action' => 'add')));
$form->prepare();
?>
<div class="asideGestion">
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('idHotel'));
    echo '<br />';
    echo $this->formRow($form->get('idAdministrateur'));
    echo '<br />';
    echo $this->formRow($form->get('nomHotel'));
    echo '<br />';
    //echo $this->formSubmit($form->get('submit'));
    ?>
    <input type="submit" name="submit" id="submitbutton" value="Ajouter" class="btn btn-success"  />
    <a href="<?php echo $this->url('hotel'); ?>" class="btn btn-success">Retour</a>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
