<?php

 $title = 'Modifier un hôtel';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'hotel',
     array(
         'action' => 'edit',
         'idHotel' => $this->idHotel,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('idAdministrateur'));
 echo '<br />';
 echo $this->formHidden($form->get('idHotel'));
 echo $this->formRow($form->get('nomHotel'));
 echo '<br />';
 echo $this->formSubmit($form->get('submit'));
 //echo $this->formSubmit($form->get('cancel'));
 echo $this->form()->closeTag();
