<?php
$title = 'Modifier un hôtel';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
                'hotel', array(
            'action' => 'edit',
            'idHotel' => $this->idHotel,
                )
));
$form->prepare();
?>

<div class="asideGestion">
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('idHotel'));
    echo $this->formRow($form->get('idAdministrateur'));
    echo '<br />';
    echo $this->formRow($form->get('nomHotel'));
    echo '<br />';
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>