<?php
$title = 'Mes Hôtels';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('hotel', array('action' => 'add')); ?>" class="Bouton">Ajouter un hôtel</a>
</p>

<?php foreach ($hotels as $hotel) : ?>
    <div class="asideHotel">
        <table>
            <tr>
                <td><img src="<?php echo $this->basePath('img/' . rand(1, 4) . '.jpg') ?>" alt="Zend Framework 2" class="imgHotel"/></td>
                <td class="Hotel" rowspan="2">
                    <p>Identifiant de l'hôtel: <?php echo $this->escapeHtml($hotel->idHotel); ?></p>
                    <p>Nom de l'hôtel: <?php echo $this->escapeHtml($hotel->nomHotel); ?></p>
                    <p>Identifiant de l'administrateur: <?php echo $this->escapeHtml($hotel->idAdministrateur); ?></p>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="<?php echo $this->url('chambre', array('action' => 'index', 'nomHotel' => $hotel->nomHotel, 'idChambre' => $hotel->idHotel)); ?>" class="btn btn-success">Gérer</a>
                    <a href="<?php echo $this->url('hotel', array('action' => 'edit', 'idHotel' => $hotel->idHotel)); ?>" class="btn btn-success">Modifier</a>
                    <a href="<?php echo $this->url('hotel', array('action' => 'delete', 'idHotel' => $hotel->idHotel)); ?>" class="btn btn-success">Supprimer</a>
                </td>
            </tr>
        </table>
    </div>
<?php endforeach; ?>