<?php
$title = 'Mes hôtels - Json';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?> <a href="index" class="btn btn-success">Normal</a></h1>
<center>
    <!-- Code par Arnaud -->
    <body ng-app="main">
        <div ng-controller="DemoCtrl">
            <p><strong>Page n°</strong> {{tableParams.page()}} <strong></p>
            <p>Nombre d'hôtels par page :</strong> {{tableParams.count()}}</p>

            <table ng-table="tableParams" class="table">
                <tr ng-repeat="hotel in $data">
                    <td data-title="'Identifiant'">{{hotel.idHotel}}</td>
                    <td data-title="'Administrateur'">{{hotel.idAdministrateur}}</td>
                    <td data-title="'Nom'">{{hotel.nomHotel}}</td>
                </tr>
            </table>
        </div>
        <p>Par Arnaud</p>
    </body>
</center>