<?php
$title = 'Mes hôtels - Json';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?> <a href="index" class="btn btn-success">Normal</a></h1>
<center>
    <div ng-app="" ng-controller="hotelsController">

        <table class="table ng-table-responsive table-condensed table-hover table-bordered table-striped">
            <tbody>
                <tr ng-repeat="h in hotels">
                    <td>{{ h.idHotel}}</td>
                    <td>{{ h.idAdministrateur}}</td>
                    <td>{{ h.nomHotel}}</td>
                </tr>
            </tbody>
        </table>

    </div>

    <script>
        function hotelsController($scope, $http) {
            $http.get("http://localhost/HotelierJson/public/hotel/listeHotelJson")
                    .success(function (response) {
                        $scope.hotels = response;
                    });
        }
    </script>
</center>