<?php

use Application\Module; ?><center><div class="jumbotron">
        <h1>Bienvenue <strong class="zf-green"><?php echo ucfirst(Module::$utilisateur->nom); ?></strong></h1>
        <p>Le gestionnaire d'hôtels <strong>Hôtelier</strong> vous permet d'ajouter des hôtels, des chambres et des extras,<br />pour gérer et étendre votre empire hôtelier.</p>
        <p><a class="btn btn-success btn-lg" href="<?php echo $this->url('hotel') ?>">Voir mes hôtels &raquo;</a></p>
    </div>

    <div class="row">

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <img src="<?php echo $this->basePath('img/log.png') ?>" alt="Hotelier" class="log"/>
                    <h3 class="panel-title">Ajouter un hôtel</h3>
                </div>
                <div class="panel-body">
                    <p>Vous pouvez ajouter un nouvel hôtel à votre gestionnaire en cliquant sur le bouton ci-dessous</p>
                    <p><a class="btn btn-success pull-right" href="<?php echo $this->url('hotel', array('action' => 'add')); ?>">Ajouter un hôtel &raquo;</a></p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <img src="<?php echo $this->basePath('img/log4.png') ?>" alt="Hotelier" class="log"/>
                    <h3 class="panel-title">Astuce</h3>
                </div>
                <div class="panel-body">
                    <p>N'oubliez pas de cliquer sur le bouton "Gérer" de vos hôtels pour avoir accès aux chambres, et aux extras.</p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <img src="<?php echo $this->basePath('img/log3.png') ?>" alt="Hotelier" class="log"/>
                    <h3 class="panel-title">Se déconnecter</h3>
                </div>
                <div class="panel-body">
                    <p>Si vous souhaitez quitter le gestionnaire d'hôtels <strong>Hôtelier</strong>, pensez à vous déconnecter.</p>
                    <p><a class="btn btn-success pull-right" href="<?php echo $this->url('login/process', array('action' => 'logout')); ?>">Déconnexion &raquo;</a></p>
                </div>
            </div>
        </div>
    </div></center>